# Generated by Django 2.1.7 on 2019-03-05 15:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('number', models.CharField(max_length=5)),
                ('details', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 12, 14, 23, 137664))),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 12, 14, 23, 137664))),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('segment', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 12, 14, 23, 138663))),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 12, 14, 23, 138663))),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Kanban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 12, 14, 23, 139663))),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 12, 14, 23, 139663))),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 12, 14, 23, 140679))),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 12, 14, 23, 140679))),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 12, 14, 23, 138663))),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 12, 14, 23, 138663))),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Company')),
                ('kind', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Kind')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 12, 14, 23, 137664))),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 12, 14, 23, 137664))),
                ('license', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.License')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 12, 14, 23, 140679))),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 12, 14, 23, 140679))),
                ('kind', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Kind')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
        migrations.AddField(
            model_name='team',
            name='workflow',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Workflow'),
        ),
        migrations.AddField(
            model_name='kanban',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Workflow'),
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
        migrations.AddField(
            model_name='address',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
    ]
