# Generated by Django 2.1.7 on 2019-03-05 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 12, 14, 48, 175102)),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 12, 14, 48, 175102)),
        ),
        migrations.AlterField(
            model_name='company',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 12, 14, 48, 176100)),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 12, 14, 48, 176100)),
        ),
        migrations.AlterField(
            model_name='kanban',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 12, 14, 48, 177100)),
        ),
        migrations.AlterField(
            model_name='kanban',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 12, 14, 48, 177100)),
        ),
        migrations.AlterField(
            model_name='kind',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 12, 14, 48, 178100)),
        ),
        migrations.AlterField(
            model_name='kind',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 12, 14, 48, 178100)),
        ),
        migrations.AlterField(
            model_name='team',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 12, 14, 48, 176100)),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 12, 14, 48, 176100)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 12, 14, 48, 175102)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 12, 14, 48, 175102)),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 12, 14, 48, 177100)),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 12, 14, 48, 177100)),
        ),
    ]
