# Generated by Django 2.1.7 on 2019-03-05 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190305_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 16, 52, 23, 59318)),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 16, 52, 23, 59318)),
        ),
        migrations.AlterField(
            model_name='company',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 16, 52, 23, 60318)),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 16, 52, 23, 60318)),
        ),
        migrations.AlterField(
            model_name='kanban',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 16, 52, 23, 61318)),
        ),
        migrations.AlterField(
            model_name='kanban',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 16, 52, 23, 61318)),
        ),
        migrations.AlterField(
            model_name='kind',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 16, 52, 23, 62307)),
        ),
        migrations.AlterField(
            model_name='kind',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 16, 52, 23, 62307)),
        ),
        migrations.AlterField(
            model_name='team',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 16, 52, 23, 60318)),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 16, 52, 23, 60318)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 16, 52, 23, 59318)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 16, 52, 23, 59318)),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 16, 52, 23, 61318)),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 5, 16, 52, 23, 61318)),
        ),
    ]
