# Generated by Django 2.1.7 on 2019-03-02 23:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('segment', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 20, 49, 7, 376347))),
            ],
        ),
        migrations.CreateModel(
            name='Kanban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 20, 49, 7, 376347))),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 20, 49, 7, 377348))),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 20, 49, 7, 375351))),
                ('company_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Company')),
                ('kind_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Kind')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 20, 49, 7, 377348))),
                ('kind_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Kind')),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 20, 49, 7, 374361)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 20, 49, 7, 375351)),
        ),
        migrations.AddField(
            model_name='team',
            name='workflow_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Workflow'),
        ),
        migrations.AddField(
            model_name='kanban',
            name='workflow_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Workflow'),
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Address'),
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='license_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='usuarios.License'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='team_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Team'),
        ),
    ]
