# Generated by Django 2.1.7 on 2019-03-03 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20190302_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kanban',
            old_name='workflow_id',
            new_name='workflow',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='kind_id',
            new_name='kind',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='workflow_id',
            new_name='workflow',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='license_id',
            new_name='license',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='team_id',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='workflow',
            old_name='kind_id',
            new_name='kind',
        ),
        migrations.AlterField(
            model_name='address',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 21, 2, 45, 430439)),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 21, 2, 45, 430439)),
        ),
        migrations.AlterField(
            model_name='company',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 21, 2, 45, 432439)),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 21, 2, 45, 432439)),
        ),
        migrations.AlterField(
            model_name='kanban',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 21, 2, 45, 432439)),
        ),
        migrations.AlterField(
            model_name='kanban',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 21, 2, 45, 432439)),
        ),
        migrations.AlterField(
            model_name='kind',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 21, 2, 45, 433438)),
        ),
        migrations.AlterField(
            model_name='kind',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 21, 2, 45, 433438)),
        ),
        migrations.AlterField(
            model_name='team',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 21, 2, 45, 431439)),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 21, 2, 45, 431439)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 21, 2, 45, 431439)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 21, 2, 45, 431439)),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 21, 2, 45, 433438)),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 21, 2, 45, 433438)),
        ),
    ]
