# Generated by Django 2.1.7 on 2019-03-03 00:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20190302_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 21, 24, 6, 308795)),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 21, 24, 6, 308795)),
        ),
        migrations.AlterField(
            model_name='company',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 21, 24, 6, 310776)),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 21, 24, 6, 310776)),
        ),
        migrations.AlterField(
            model_name='kanban',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 21, 24, 6, 310776)),
        ),
        migrations.AlterField(
            model_name='kanban',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 21, 24, 6, 310776)),
        ),
        migrations.AlterField(
            model_name='kind',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 21, 24, 6, 312794)),
        ),
        migrations.AlterField(
            model_name='kind',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 21, 24, 6, 312794)),
        ),
        migrations.AlterField(
            model_name='team',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 21, 24, 6, 309775)),
        ),
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 21, 24, 6, 309775)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 21, 24, 6, 309775)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 21, 24, 6, 309775)),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='create_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 21, 24, 6, 311778)),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 2, 21, 24, 6, 311778)),
        ),
    ]
